import Navbar from './navbar'
export { Navbar };
export { default as Home } from './home.jsx'
export { default as Statistics } from './statistics'
export { default as Contract } from './contract'
export { default as Billing } from './billing'
export { default as Business } from './business'
export { default as CTA } from './cta'
export { default as Testimonials } from './testimonials'
export { default as Clients } from './clients'
export { default as Footer } from './footer'
